import React, { ReactNode } from 'react'
import Navbar from '@/components/navbar'
import './page.scss'

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body>
        <div id='root'>
          <Navbar></Navbar>
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default RootLayout
